---
# tasks file for deploy_uac

- include_tasks: generate-evidence.yml
  when: ansible_facts['system'] == "Linux"

- include_tasks: retrieve-evidence.yml
  when: (ansible_facts['system'] == "Linux") and
        (uac_retrieve_evidence == "true")

- include_tasks: generate-evidence.yml
  when: ansible_facts['system'] == "FreeBSD"

- include_tasks: retrieve-evidence.yml
  when: (ansible_facts['system'] == "FreeBSD") and
        (uac_retrieve_evidence == "true")

# TO DO: test on OpenBSD