---
# install_ansible/tasks/pipx.yml

# Add ~/.local/bin to the $PATH so any install of pipx can be used, not
# just the /usr/bin/pipx binaries.
- name: Install Ansible (pipx)
  ansible.builtin.shell: |
    set -o pipefail
    export PATH="$PATH:/home/$USER/.local/bin"
    pipx install --include-deps ansible
  args:
    executable: /bin/bash
