---
# install_pipx/tasks/apt.yml

- name: Install pipx (apt)
  ansible.builtin.apt:
    pkg:
      - pipx
    state: latest
    update_cache: true
  become: true
  become_method: ansible.builtin.sudo
