---
# install_pipx/tasks/ensure-path.yml

- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Pipx ensurepath (system package)
  ansible.builtin.command: pipx ensurepath
  when: "'pipx' in ansible_facts.packages"

- name: Pipx ensurepath (pip module)
  ansible.builtin.command: python3 -m pipx ensurepath
  when: "'pipx' not in ansible_facts.packages"
