---
# tasks file for install_pipx

- name: Install pipx (apt)
  include_tasks: apt.yml
  when: (ansible_facts["distribution"] == "Kali")

- name: Install pipx (dnf)
  include_tasks: dnf.yml
  when: ansible_facts["distribution"] == "Fedora"

- name: Install pipx (pip)
  include_tasks: pip.yml
  when: (ansible_facts["distribution"] not in ["Kali", "Fedora"])

- name: Run ensurepath
  include_tasks: ensure-path.yml
