---
# install_pipx/tasks/pip.yml

# https://packaging.python.org/en/latest/specifications/externally-managed-environments/
# https://github.com/geerlingguy/ansible-role-pip/blob/master/tasks/main.yml
- name: Check for EXTERNALLY-MANAGED file
  ansible.builtin.stat:
    path: /usr/lib/python3.{{ ansible_python.version.minor }}/EXTERNALLY-MANAGED
  register: externally_managed

- name: Install pipx within the user home directory
  ansible.builtin.pip:
    name: pipx
    extra_args: --user --break-system-packages
  when: externally_managed.stat.exists

- name: Install pipx within the user home directory
  ansible.builtin.pip:
    name: pipx
    extra_args: --user
  when: not externally_managed.stat.exists
