---
# inventory/inventory.yml

# https://docs.ansible.com/ansible/latest/inventory_guide/connection_details.html
# https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html
# https://docs.ansible.com/ansible/latest/getting_started/index.html
# ansible all --list-hosts -i inventory/inventory.yml

# A sample yaml inventory file

localgroup:
  hosts:
    localhost:
      ansible_connection: local
    #127.0.0.1:
      #ansible_port: 2222
      #ansible_user: user
      #per_host_var: "some_value"
  vars:
    #per_group_var: "some_other_value"
    #per_group_list:
      #- list_item_1
      #- list_item_2

manager_group:
  hosts:
    #10.20.30.40:
      #ansible_port: 22
      #ansible_user: admin
      #ansible_become_password: "{{ admin_sudo_pass }}"
      #ansible_become_method: sudo
    #10.20.30.41:
      # Windows endpoint with WinRM over SSH example
      #ansible_port: 22
      #ansible_user: win_user
      #ansible_become_password: "{{ win_user_runas_pass }}"
      #ansible_become_method: runas
      #ansible_connection: ssh
      #ansible_shell_type: cmd
  vars:
    #is_manager: "true"
    #is_tester: "true"

managed_group:
  hosts:
    #172.16.20.20:
      #ansible_port: 22
      #ansible_user: root
  vars:
    #is_managed: "true"
    #is_target: "true"