## Write DNS queries / replies to /var/log/syslog
## Place this file under /etc/unbound/unbound.conf.d/* (Debian)
## Place this file under /etc/unbound/conf.d/* (RedHat)

server:

## Logging
#	log-queries: yes
	log-replies: yes
#	log-tag-queryreply: yes

