---
# build_ubuntu_desktop/tasks/apt.yml

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/debconf_module.html
# https://askubuntu.com/questions/1498205/ubuntu-server-22-04-how-to-write-the-ansible-debconf-values-into-postfix-config
# This will create the wireshark group, so group members do not need to run wireshark elevated as root
- name: Preseed Wireshark configuration
  ansible.builtin.debconf:
    name: "wireshark-common"
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  with_items:
    - { question: "wireshark-common/install-setuid", value: ": true", vtype: "select" }
  become: yes
  become_method: sudo

# Install a selection of packages useful for a desktop environment
- name: Install apt Packages
  ansible.builtin.apt:
    pkg:
      - apparmor-utils
      - cryptsetup
      - curl
      - git
      - hexedit
      - htop
      - libimage-exiftool-perl
      - libpam-google-authenticator
      - nmap
      - pcscd
      - poppler-utils
      - python3-pip
      - python3-venv
      - qrencode
      - resolvconf
      - scdaemon
      - screen
      - tmux
      - wireguard
      - wireshark
    update_cache: yes
  become: yes
  become_method: sudo

# Remove a selection of packages often installed by default
- name: Remove apt Packages
  ansible.builtin.apt:
    pkg:
      - evince
    autoremove: yes
    purge: yes
    state: absent
  become: yes
  become_method: sudo