---
# build_ubuntu_desktop/tasks/gnome.yml

# Configure GNOME desktop settings with dconf / gsettings
- name: Install GNOME configuration scripts
  ansible.builtin.copy:
    remote_src: no
    src: "{{ item }}"
    dest: /usr/local/bin/
    mode: '0755'
    owner: root
    group: root
  loop:
    - "dconf.sh"
    - "gsettings.sh"
  become: yes
  become_method: sudo

- name: Run GNOME configuration scripts (user)
  ansible.builtin.shell:
    cmd: /usr/local/bin/gsettings.sh

- name: Run GNOME configuration scripts (system)
  ansible.builtin.shell:
    cmd: /usr/local/bin/dconf.sh
  become: yes
  become_method: sudo