---
# manage_accounts/tasks/expire-passwords.yml

- name: "Run passwd --expire on user"
  ansible.builtin.command: passwd --expire {{ ansible_user_id }}
  when: user_list == []
  become: true
  become_method: ansible.builtin.sudo

- name: "Run passwd --expire on list of users"
  ansible.builtin.command: passwd --expire "{{ item }}"
  loop: "{{ user_list }}"
  when: user_list != []
  become: true
  become_method: ansible.builtin.sudo
