---
# install_vscode/tasks/apt.yml

# This uses the same signing key used by Microsoft's PMC service, but requires an additional sources list.
# On newer distro versions, it relies on the older key (not the microsoft-2025.asc key), which the
# configure_microsoft_repos role will still pull, even if it doesn't use it as the primary key.
# https://code.visualstudio.com/docs/setup/linux#_debian-and-ubuntu-based-distributions
- name: Add VSCode repository info
  ansible.builtin.deb822_repository:
    name: "vscode"
    types: deb
    uris: "https://packages.microsoft.com/repos/code"
    suites: 'stable'
    components: main
    architectures:
      - amd64
      - armhf
      - arm64
    signed_by: "/etc/apt/keyrings/microsoft.asc"
  when: ansible_facts['distribution'] != "Kali"
  become: true
  become_method: ansible.builtin.sudo

- name: "Install VSCode / code (Debian / Ubuntu)"
  ansible.builtin.apt:
    pkg:
      - code
    state: latest
    update_cache: yes
  when: ansible_facts['distribution'] != "Kali"
  become: yes
  become_method: sudo

# Kali ships its own version of VScode as 'code-oss'
# https://www.kali.org/blog/kali-linux-2021-2-release/#new-tools-in-kali
- name: "Install VSCode / code-oss (Kali)"
  ansible.builtin.apt:
    pkg:
      - code-oss
    state: latest
    update_cache: yes
  when: ansible_facts['distribution'] == "Kali"
  become: yes
  become_method: sudo