---
# install_vscode/tasks/snap.yml

# https://code.visualstudio.com/docs/setup/linux

- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto

# Install a selection of snap packages, typically for a guest VM
- name: Install VSCode (snap)
  ansible.builtin.shell: |
    snap install --classic code # or code-insiders
  args:
    executable: /bin/bash
  when: ("'snap' in ansible_facts.packages") and
        (ansible_facts['distribution'] == "Ubuntu")
  become: yes
  become_method: sudo