---
# tasks file for update-packages
# update-packages/tasks/main.yml

- include_tasks: apt.yml
  when: ansible_facts['os_family'] == "Debian"

- include_tasks: dnf.yml
  when: ansible_facts['os_family'] == "RedHat"