---
# tasks file for configure_gnupg

- include_tasks: config.yml

- include_tasks: apt.yml
  when: ansible_facts['os_family'] == "Debian"

# TO DO
#- include_tasks: dnf.yml
#  when: ansible_facts['os_family'] == "RedHat"
