---
# configure_hashicorp_repos/tasks/apt.yml

# This configures the repo manually using /etc paths, avoiding the deprecated
# apt-key commmand and module.

# https://developer.hashicorp.com/packer/tutorials/docker-get-started/get-started-install-cli
- name: Obtain Hashicorp's signing key
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /tmp/hashicorp.asc
    mode: '0644'

# https://www.hashicorp.com/en/trust/security
- name: Verify Hashicorp's signing key
  ansible.builtin.shell: |
    set -o pipefail
    gpg /tmp/hashicorp.asc | grep -P "798A\s?EC65\s?4E5C\s?1542\s?8C8E\s?\s?42EE\s?AA16\s?FCBC\s?A621\s?E701"
  args:
    executable: /bin/bash

- name: Install Hashicorp's signing key
  ansible.builtin.shell: |
    set -o pipefail
    if [ -f /etc/apt/keyrings/hashicorp.gpg ]; then rm -f /etc/apt/keyrings/hashicorp.gpg; fi
    gpg -o /etc/apt/keyrings/hashicorp.gpg --dearmor /tmp/hashicorp.asc
  args:
    executable: /bin/bash
  become: true
  become_method: ansible.builtin.sudo

# This differs from the original instructions because it points to the gpg key
# file we write in /etc/apt/keyrings/hashicorp.gpg
- name: Configure the apt sources list file
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/hashicorp.list
    owner: root
    group: root
    mode: '0644'
    backup: true
    content: |
      deb [arch=amd64 signed-by=/etc/apt/keyrings/hashicorp.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
  become: true
  become_method: ansible.builtin.sudo

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 0
  become: true
  become_method: ansible.builtin.sudo
